site_name: Marbles
repo_url: https://github.com/sjiang2019/sjiang2019.github.io
repo_name: blog
theme:
  name: material
  font:
    text: Inter
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.footer
    - search.suggest
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  logo: assets/ocean_marble.png
  favicon: assets/ocean_marble.png
copyright: Copyright &copy; 2024
extra:
  generator: false
plugins:
  - search
  - blog:
      blog_dir: "./writing"
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
